name: IG Publishing
run-name: ${{ github.actor }} is building the IG

on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: ruby/setup-ruby@v1
    - run: gem install -N jekyll
    - run: npm install -g fsh-sushi
    - run: ./_updatePublisher.sh -y
    - run: ./_genonce.sh

    - name: GH Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: output

